### ISSUE TITLE
reprodcing issue

### ISSUE THREAD

**Issue by chenghao-shi** [robot-learning-freiburg/LCDNet#10]
Hi!

Thanks for sharing! The performance of LCDNet on loop closure detection is remarkable. I have been attempting to reproduce the experimental results of the paper, but I encountered issues with the inference_yaw_general.py script. **While I was able to successfully replicate the paper's results using inference_loop_closure.py, the estimated rotations and translations generated by inference_yaw_general.py were consistently close to 0 and failed to produce reasonable outputs**,  with RANSAC or withou RANSAC. 
Can you provide some insights of what could be causing this issue, and how can I better debug the issue?
Following are my configs:
 parser.add_argument('--root_folder', default='/mnt/Mount/Dataset/KITTI_odometry',
                        help='dataset directory')
    parser.add_argument('--weights_path', default='/home/chenghao/DL_workspace/loop-closing/LCDNet/checkpoints/LCDNet-kitti360.tar')
    parser.add_argument('--num_iters', type=int, default=1)
    parser.add_argument('--dataset', type=str, default='kitti')
    parser.add_argument('--ransac', action='store_true', default=True)
    parser.add_argument('--teaser', action='store_true', default=False)
    parser.add_argument('--icp', action='store_true', default=False)
    parser.add_argument('--remove_random_angle', type=int, default=-1)
    parser.add_argument('--validation_sequence', type=str, default='00')
    parser.add_argument('--without_ground', action='store_true', default=True,
                        help='Use preprocessed point clouds with ground plane removed')
    args = parser.parse_args() 

Moreover, I was wondering if it would be possible to release the pre-trained model on KITTI? It would be better if I can use this model for further test. Thank you!

**Comment by cattaneod** [comment]
Hi,
thank you for you interest, and sorry for the late reply.

In order to help you, I would need some more information:

Which sequence are you using for evaluation?
Which variables are "consistently close to 0"? If you mean the final output, that's normal, as that represent the error, not the predicted rotations and translations.

If you mean the _transformation_ variable, can you try without RANSAC and check if that solves the issue? We noticed that the RANSAC implementation in Open3D has very different results depending on the library version.

**Comment by chenghao-shi** [comment]
Hi,
thank your for replying! I test on KITTI seq 00, following are first ten outputs without RANSAC:
```
estimated transformation:  tensor([ 1.0351,  0.4585, -0.0815]) tensor(6.2357)
trans error:  tensor(3.2412) yaw error:  tensor(71.5625)

estimated transformation:  tensor([ 0.6213,  0.5443, -0.0831]) tensor(6.2256)
trans error:  tensor(3.2575) yaw error:  tensor(67.5136)

estimated transformation:  tensor([ 1.1579,  0.4833, -0.0719]) tensor(6.2318)
trans error:  tensor(3.5551) yaw error:  tensor(64.6259)

estimated transformation:  tensor([ 0.7370,  0.4650, -0.0332]) tensor(0.0030)
trans error:  tensor(3.6356) yaw error:  tensor(64.5555)

estimated transformation:  tensor([ 0.7055,  1.4349, -0.1246]) tensor(6.2756)
trans error:  tensor(2.3641) yaw error:  tensor(77.6212)

estimated transformation:  tensor([ 0.4158,  1.0763, -0.1148]) tensor(6.2631)
trans error:  tensor(2.5404) yaw error:  tensor(73.2425)

estimated transformation:  tensor([ 0.2848,  0.3993, -0.1207]) tensor(6.2660)
trans error:  tensor(3.0142) yaw error:  tensor(69.7811)

estimated transformation:  tensor([ 0.0231,  0.6930, -0.1325]) tensor(6.2822)
trans error:  tensor(2.7539) yaw error:  tensor(67.2395)

estimated transformation:  tensor([ 0.4128,  0.7308, -0.1141]) tensor(6.2820)
trans error:  tensor(2.6558) yaw error:  tensor(63.9814)

estimated transformation:  tensor([-0.4194,  0.1842, -0.0816]) tensor(0.0003)
trans error:  tensor(3.2344) yaw error:  tensor(60.8846)

estimated transformation:  tensor([-0.4721,  0.1401, -0.0682]) tensor(6.2680)
trans error:  tensor(3.3041) yaw error:  tensor(57.0993)
```
I can ensure that the generated ground truth pairs and transformations are correct, as I have tested them using other methods. Here is an example where I used the ground truth transformation to register the pair:
![ScreenCapture_2023-07-11-09-24-17](https://github.com/robot-learning-freiburg/LCDNet/assets/73333544/d97347dd-1779-41f5-a259-f873be0bab08)

What is really confusing me is that the loop detection results are fine, but the loop closing fails :(

**Comment by cattaneod** [comment]
I cannot reproduce your error. This is my output for the first 10 pairs of sequence 00 without RANSAC:
```
estimated transformation: tensor([0.2611, 2.5703, 0.0078]) 5.034829139709473
trans error: 1.482973337173462 yaw error: 2.7558720111846924

estimated transformation: tensor([-0.2408,  2.6878, -0.0272]) 5.108007431030273
trans error: 1.428804636001587 yaw error: 3.4822216033935547

estimated transformation: tensor([-0.7091,  2.8341, -0.0038]) 5.1645941734313965
trans error: 1.2761472463607788 yaw error: 3.4780688285827637

estimated transformation: tensor([-1.4351,  2.4813,  0.0342]) 5.2330780029296875
trans error: 1.66987144947052 yaw error: 4.218625068664551

estimated transformation: tensor([0.9349, 1.4267, 0.0172]) 5.01531982421875
trans error: 2.1825995445251465 yaw error: 5.4127607345581055

estimated transformation: tensor([0.7026, 1.8487, 0.0133]) 5.02756929397583
trans error: 1.774394154548645 yaw error: 2.454141616821289

estimated transformation: tensor([ 5.7260e-01,  2.2821e+00, -1.8674e-03]) 5.088119029998779
trans error: 1.2408798933029175 yaw error: 2.2921295166015625

estimated transformation: tensor([ 0.1138,  2.5597, -0.0365]) 5.161681652069092
trans error: 1.0687803030014038 yaw error: 3.040663480758667

estimated transformation: tensor([-0.4427,  2.5276, -0.0119]) 5.2071332931518555
trans error: 1.1297765970230103 yaw error: 2.3986258506774902

estimated transformation: tensor([-1.0043,  2.2776,  0.0187]) 5.278475284576416
trans error: 1.3657351732254028 yaw error: 3.3030521869659424
```

And with RANSAC:
```
estimated transformation: tensor([1.2571, 3.7451, 0.0997]) 4.992386817932129
trans error: 0.06704861245980474 yaw error: 0.3241061270236969

estimated transformation: tensor([ 0.5897,  3.8520, -0.0298]) 5.049684047698975
trans error: 0.11133165037585879 yaw error: 0.14053796231746674

estimated transformation: tensor([-0.0965,  3.9430,  0.0249]) 5.106630325317383
trans error: 0.1695980594912397 yaw error: 0.1569850593805313

estimated transformation: tensor([-0.5691,  3.7989,  0.0327]) 5.158931255340576
trans error: 0.09679017666323607 yaw error: 0.029670340940356255

estimated transformation: tensor([2.5977, 2.8331, 0.2693]) 4.926833629608154
trans error: 0.18846125346866577 yaw error: 0.34287548065185547

estimated transformation: tensor([1.9004, 2.9979, 0.0922]) 4.987635135650635
trans error: 0.12401411455163111 yaw error: 0.16608287394046783

estimated transformation: tensor([1.4544, 3.1367, 0.1108]) 5.052154541015625
trans error: 0.07379225972070995 yaw error: 0.23151609301567078

estimated transformation: tensor([ 0.9530,  3.4072, -0.0289]) 5.106949329376221
trans error: 0.14528954800381386 yaw error: 0.09526747465133667

estimated transformation: tensor([0.0493, 3.2372, 0.0184]) 5.16341495513916
trans error: 0.28698346371699335 yaw error: 0.10625042021274567

estimated transformation: tensor([-0.1855,  3.4660, -0.0731]) 5.219388961791992
trans error: 0.14907817085872033 yaw error: 0.08234475553035736
```

What version of pytorch, spconv, pcdet and open3d are you using?

**Comment by chenghao-shi** [comment]
I use  
`pcdet 0.3.0
open3d  0.12.0
spconv-cu114 2.1.18
pytorch 1.8.0`

**Comment by cattaneod** [comment]
I cannot really test using the same version that you have, as pytorch 1.8.0 binaries only support up to cuda 11.1, while it seems that you have cuda 11.4. Therefore I would have to compile pytorch from source. 

Can you try with a _tested_ cuda version (11.1 or 11.3), and relative library versions in a new python environment?

**Comment by chenghao-shi** [comment]
sure, I will try updating my lib, thank you!



---Original---
From: "Daniele ***@***.***&gt;
Date: Tue, Jul 11, 2023 23:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [robot-learning-freiburg/LCDNet] reprodcing issue (Issue #10)




 
I cannot really test using the same version that you have, as pytorch 1.8.0 binaries only support up to cuda 11.1, while it seems that you have cuda 11.4. Therefore I would have to compile pytorch from source.
 
Can you try with a tested cuda version (11.1 or 11.3), and relative library versions?

**Comment by chenghao-shi** [comment]
It seems that CUDA 11.4 (or other libraries required by CUDA 11.4) conflicts with the current version of the code. I ran the code on a new environment with CUDA 11.3 and obtained fine results. Thank you for your assistance and for sharing your excellent work.

**Comment by cattaneod** [comment]
I'm glad that you solved the issue.
