### ISSUE TITLE
Incorrect index used while generating the training dataset 

### ISSUE THREAD

**Issue by girishbathala** [robot-learning-freiburg/LCDNet#11]
Hi,

Congrats on the great work.

I have a question regarding the sample generated when the `train` flag is enabled in the `KITTILoader3DPoses` and/or `KITTI3603DPoses` 

The index used in this line (https://github.com/robot-learning-freiburg/LCDNet/blob/main/datasets/KITTIDataset.py#L109)  should ideally be the following. Use the variable `i` instead of `idx` to get the positive and negative match. Otherwise, this would always be comparing with the anchor pose for all iterations 

```
                i = random.choice(indices)
                possible_match_pose[0] = self.poses[i][0, 3]
                possible_match_pose[1] = self.poses[i][1, 3]
                possible_match_pose[2] = self.poses[i][2, 3]
                distance = torch.norm(anchor_pose - possible_match_pose)
```

**Comment by cattaneod** [comment]
Hi,

the code snippet you highlighted is indeed incorrect, however, it is never used. The `KITTILoader3DPoses` and `KITTI3603DPoses` are only used for evaluation, while for training we use `KITTI3603DDictPairs` and `KITTILoader3DDictPairs`. I will remove that part of the code to avoid any confusion.

Thank you for pointing that out.
