### ISSUE TITLE
using point cloud not centered around origin

### ISSUE THREAD

**Issue by jonathan-besuchet** [robot-learning-freiburg/LCDNet#4]
Hello,
Congrate for the nice work!

I was wondering if the network handles correctly the global position of points in the input point cloud (ex: a point cloud with points coordinate far away from origin) or if it is expecting to receive the point cloud as scans (= points centered around the origin with a given max range).
I would be interested to know specifically:
- if the same point cloud around origin and shifted 500m away from origin would give the same  global descriptors
- if the network would give correct transform between two overlapping point clouds away from origin

I guess if this is not the case one can just compute the barrycenter of the point clouds and shift them to the origin, and then do the global descriptor and transform computation.

Thanks for your answers.

**Comment by cattaneod** [comment]
Hello,
thank you for your interest in our work!

our network expects the input point clouds as scans, with the LiDAR sensor being the origin of the point cloud. If you don't know the transformation between the world frame and the scan frame, computing the centroid and shift the points could be a possible solution.

**Comment by jonathan-besuchet** [comment]
great thanks for your quick answer.
