### ISSUE TITLE
Question about integration to LIO-SAM

### ISSUE THREAD

**Issue by Taeyoung96** [robot-learning-freiburg/LCDNet#5]
@cattaneod   
Thanks for your great work!  

I have a question about integrating to [LIO-SAM](https://github.com/TixiaoShan/LIO-SAM).  
As you know, LIO-SAM is based on C++ and uses ROS programming.  

However, LCDNet is based on Python and uses Pytorch or other python packages.  

Maybe I'm not familiar with that, I wonder how to integrate these two algorithms.  
Did you make your own LCDNet ROS packages?  
Is it possible to use other SLAM algorithms besides LIO-SAM?  

I would appreciate it if you could give me an engineering tip. :smile:   

Thanks,

**Comment by cattaneod** [comment]
Thank you for your interest in our work!

To combine LCDNet with LIO-SAM, I wrote a python ROS package that communicate with LIO-SAM using few additional topics.

The workflow looks something like this:

* LIO-SAM publish the point-cloud of each keyframe in a topic (e.g. `/lio_sam/mapping/keyframes`)
* LCDNetNode subscribe to the same topic, generate the global descriptor for each keyframe, and save it in a FAISS index
* LCDNetNode compare the global descriptor of the current frame with the ones from the FAISS index (ignoring the past N frames), and if a loop is detected, it publish the pair in a topic (e.g., `/loop_closure_from_python`), together with the predicted 6-DoF transformation.
* LIO-SAM subscribe to the same topic, and when a pair is published, it will run ICP (using the predicted transformation as initial guess), and add the loop to the graph if the ICP fitness is higher than a threshold.

Obviously, a similar workflow can be implemented in any SLAM system.

**Comment by Taeyoung96** [comment]
@cattaneod   
I fully understand it! Thanks for your comments :smile:
