### ISSUE TITLE
integration with LIO-SAM

### ISSUE THREAD

**Issue by arkin8858** [robot-learning-freiburg/LCDNet#7]
@cattaneod 
First of all i would like to appreciate and thanks for your great efforts on this project.
I've implemented this code with kitti old odometry dataset and received quite promising results. I've few question mentioned below;
1- This code must need groundtruth which means its supervised learning. is it possible to test your architecture with self-supervised and if yes then how could we do that?
2- I've modified a code to save the 6dof poses and compare them with the groundtruth as well but how could we integrate this with the LIO-SAM. I checked previous questions and you mentioned few steps but i believe its not simple task. Is there any possibility that you could opensource that integration with LIO-SAM code as well? Such as https://github.com/leggedrobotics/delora  have published their code integration part with LOAM as well. 

Looking forward to your feedback ! 
Regards
Arkin

**Comment by cattaneod** [comment]
Dear @arkin8858,

LCDNet is fully supervised, as it requires 6-DoF transformations between point clouds. We didn't test it with self-supervised training. Feel free to try any self-supervised loss, there are various papers in that direction. But it won't be an easy task. I can't help further with that.

Regarding the integration with LIO-SAM, I'm afraid we won't release the integration soon. We are refactoring our SLAM pipeline, and it will probably takes some times before we'll be able to open source it.
