### ISSUE TITLE
How to Run LIO-SAM with LCDNet on KITTI sequence 02

### ISSUE THREAD

**Issue by PeiliSong501** [robot-learning-freiburg/LCDNet#8]
Dear Author:
First of all, I really appreciate your project, and thank you very much to opensource your code.
I've read your paper and watched your video, and I noticed that you test your new LIO-SAM system integrated with LCDNet on sequence 02 of KITTI dataset. To my best knowledge, IMU data wasn't provided in KITTI odometry benchmark(Meanwhile, KITTI raw data provides IMU/GPS data but lack of ground truth). I believe that's why LIO-SAM's GitHub page claims that "Since LIO-SAM needs a high-frequency IMU for function properly, we need to use KITTI raw data for testing." How did you overcome the problem of the missing IMU data in sequence 02?
I would like to integrate your work with other state-of-the-art Lidar SLAM systems as well, and I'm hoping to test them on KITTI odometry sequences if possible. So I'll be very grateful if you can answer my little question.

**Comment by cattaneod** [comment]
Dear @Bazinga92445,

thank you for your interest in our research!
Regarding the KITTI Odometry dataset, it's actually possible to retrieve the IMU data for the sequences.
In the "KITTI odometry development kit", available [here](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_odometry.zip), there is a mapping between the odometry sequences and the raw data. Therefore, it is possible to use the undistorted scan from the odometry dataset, and the relative IMU data from the RAW data.

**Comment by PeiliSong501** [comment]
Thank you very much for your thoughtful reply! Actually I've found out the mapping scheme earlier, but I did forget about the devkit.
